// Optional DOM-only integration check. No browser or external model request is used.
// Point CHATAXI_DOM_MODULE to a locally installed linkedom module; it is never shipped.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
if (!process.env.CHATAXI_DOM_MODULE) throw Error('Set CHATAXI_DOM_MODULE to a test-only linkedom installation');
const { parseHTML } = require(process.env.CHATAXI_DOM_MODULE);
const root = fileURLToPath(new URL('../', import.meta.url));
const { window, document } = parseHTML(fs.readFileSync(root + 'index.html', 'utf8'));
const data = new Map();
Object.defineProperty(document, 'activeElement', { get() { return this._focus || this.body; } });
window.HTMLElement.prototype.focus = function () { document._focus = this; };
window.HTMLElement.prototype.getClientRects = function () { return [1]; };
Object.defineProperty(window.HTMLElement.prototype, 'elements', { get() { return { namedItem: name => this.querySelector('[name="' + name + '"]') }; } });
Object.defineProperty(window.HTMLInputElement.prototype, 'checked', { get() { return this.hasAttribute('checked'); }, set(value) { if (value) this.setAttribute('checked', ''); else this.removeAttribute('checked'); } });
Object.defineProperty(window.HTMLSelectElement.prototype, 'value', { get() { const option = this.querySelector('option[selected]') || this.querySelector('option'); return option ? option.value : ''; }, set(value) { this.querySelectorAll('option').forEach(option => { if (option.value === value) option.setAttribute('selected', ''); else option.removeAttribute('selected'); }); } });
Object.defineProperty(window.HTMLTextAreaElement.prototype, 'maxLength', { get() { return Number(this.getAttribute('maxlength') || -1); } });
const location = { hash: '#/conversations' };
const history = { state: null, replaceState(state, _, hash) { this.state = state; location.hash = hash; }, pushState(state, _, hash) { this.state = state; location.hash = hash; }, back() {} };
const context = vm.createContext({ window, document, location, history, navigator: { language: 'zh-CN', languages: ['zh-CN'] }, MutationObserver: window.MutationObserver, localStorage: { get length() { return data.size; }, key(i) { return [...data.keys()][i]; }, getItem(key) { return data.get(key) ?? null; }, setItem(key, value) { data.set(key, value); }, removeItem(key) { data.delete(key); } }, URL, Blob, TextEncoder, Uint8Array, Uint32Array, btoa, atob, console, setTimeout, clearTimeout, AbortController, Event: window.Event, requestAnimationFrame: fn => setTimeout(fn, 0) });
const scripts = [...fs.readFileSync(root + 'index.html', 'utf8').matchAll(/<script src="\.\/([^\"]+)"/g)].map(match => match[1]);
for (const script of scripts) vm.runInContext(fs.readFileSync(root + script, 'utf8'), context, { filename: script });
const app = window.chataxi;
app.platform.hermit.awaitReady = async () => false;
app.platform.hermit.info = async () => ({ runtimeMode: 'browser', bridgeMode: 'none' });
app.services.tts.stop = async () => {};
const tick = () => new Promise(resolve => setTimeout(resolve, 0));
async function until(fn, description) { for (let i = 0; i < 250; i++) { if (fn()) return; await tick(); } throw Error(description + '\n' + document.body.textContent.slice(-1500)); }
function field(name, value) { const node = document.querySelector('#modalForm [name="' + name + '"]'); assert.ok(node, name); if (arguments.length > 1) { if (node.type === 'checkbox') node.checked = value; else node.value = value; } return node; }
function submit() { document.querySelector('#modalForm').dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true })); }
function click(selector) { const node = document.querySelector(selector); assert.ok(node, selector); node.click(); }
function type(selector, text) { const node = document.querySelector(selector); node.value = text; node.dispatchEvent(new window.Event('input', { bubbles: true })); }
document.dispatchEvent(new window.Event('DOMContentLoaded'));
await until(() => document.querySelector('[data-create]'), 'boot');
assert.equal(document.querySelector('#pageSubtitle').textContent, '想聊就聊，自由自在');
assert.ok(document.querySelector('.welcome-emblem .fa-comment-dots'));
let copiedGuideAddress = ''; app.platform.hermit.copyText = async value => { copiedGuideAddress = value; };
click('[data-connection-guide]');
await until(() => document.querySelector('.subsheet [data-guide-tab="beginner"]'), 'connection guide');
assert.ok(document.querySelector('.subsheet.connection-guide-sheet'));
assert.deepEqual(Array.from(document.querySelectorAll('.subsheet [data-guide-tab]')).map(button => button.textContent), ['新手', '专业', '国际', '问题']);
assert.match(document.querySelector('[data-guide-panel="beginner"]').textContent, /DeepSeek[\s\S]*Kimi[\s\S]*硅基流动/);
assert.equal(document.querySelectorAll('[data-guide-panel="beginner"] a').length, 0);
assert.equal(document.querySelector('[data-guide-panel="beginner"] code').textContent, 'https://platform.deepseek.com/api_keys');
const guideUrl = document.querySelector('[data-copy-url="https://platform.deepseek.com/api_keys"]');
assert.ok(guideUrl.querySelector('code')); assert.ok(guideUrl.querySelector('.fa-copy'));
assert.equal(guideUrl.firstElementChild.classList.contains('fa-copy'), true);
click('[data-copy-url="https://platform.deepseek.com/api_keys"]'); await until(() => copiedGuideAddress === 'https://platform.deepseek.com/api_keys', 'guide address copy');
click('.subsheet [data-guide-tab="professional"]'); assert.match(document.querySelector('[data-guide-panel="professional"]:not(.is-hidden)').textContent, /Ollama 软件/);
click('.subsheet [data-guide-tab="international"]'); assert.match(document.querySelector('[data-guide-panel="international"]:not(.is-hidden)').textContent, /OpenRouter[\s\S]*Requesty[\s\S]*302\.AI/);
click('.subsheet [data-guide-tab="troubleshooting"]'); assert.match(document.querySelector('[data-guide-panel="troubleshooting"]:not(.is-hidden)').textContent, /智能体开发模式/);
app.components.closeSubsheet();
click('[data-create]');
await until(() => document.querySelector('#modalForm [name="apiKey"]'), 'guided model service form');
assert.match(document.querySelector('[data-fetch-models]').textContent, /获取模型列表/);
assert.match(document.querySelector('[data-test-model]').textContent, /连接并测试/);
// 目录没获取成功之前，提交按钮就是「获取模型列表」。
assert.equal(document.querySelector('#modalSubmit').textContent, '获取模型列表');
assert.equal(document.querySelector('#modalSubmit').dataset.mode, 'fetch');
app.platform.network.requestJson = async options => options.method === 'GET'
  ? { data: { data: [{ id: 'gpt-4.1', owned_by: 'openai', supported_parameters: ['temperature'] }] } }
  : { data: { output_text: 'OK' } };
field('apiKey', 'fixture-key'); submit();
await until(() => document.querySelector('#modalSubmit').textContent === '保存设置', 'submit button turns into save after a successful catalog fetch');
assert.equal(document.querySelector('#modalSubmit').dataset.mode, 'save');
assert.ok(document.querySelector('#modalForm'), 'fetching the catalog through the submit button keeps the editor open');
assert.match(document.querySelector('[data-picker="externalModelId"] [data-picker-label]').textContent, /gpt-4\.1/);
assert.match(document.querySelector('#catalogStatus').textContent, /请选择一个模型。/);
assert.equal(document.querySelector('.model-toggle'), null, 'one model card does not expose a multi-model switch list');
click('[data-picker="externalModelId"]'); await until(() => document.querySelector('.subsheet .choice-group-label'), 'grouped model choice sheet');
assert.match(document.querySelector('.subsheet .choice-group-label').textContent, /推荐用于对话模型/); click('.subsheet [data-choice="gpt-4.1"]'); await tick();
click('[data-test-model]'); await until(() => /连接成功/.test(document.querySelector('#connectionStatus').textContent), 'guided model test');
field('enabled', true); submit();
await until(() => document.querySelector('#modalForm [name="systemPrompt"]'), 'guided role form');
assert.ok(document.querySelector('#avatarPreview .fa-user'), 'unnamed role uses the user icon fallback');
assert.equal(document.querySelector('[data-role-avatar-name]').textContent, '未命名');
assert.equal(document.querySelector('.avatar-copy > small').textContent, '点击头像更换');
type('#modalForm [name="name"]', '临时角色'); assert.equal(document.querySelector('[data-role-avatar-name]').textContent, '临时角色');
type('#modalForm [name="name"]', ''); assert.equal(document.querySelector('[data-role-avatar-name]').textContent, '未命名');
assert.ok(document.querySelector('[data-open-role-templates]'), 'new role editor exposes the template gallery');
assert.equal(document.querySelector('[data-open-role-templates] span').textContent, '使用模版');
click('[data-open-role-templates]'); await until(() => document.querySelector('.role-template-grid'), 'role template gallery');
assert.equal(document.querySelector('.role-template-help').textContent, '点击角色卡片直接应用');
assert.deepEqual(Array.from(document.querySelectorAll('[data-template-tab]')).map(button => button.textContent), ['全部', '男性', '女性', '其他']);
assert.equal(document.querySelectorAll('[data-role-template]').length, 27);
assert.equal(document.querySelectorAll('[data-role-template]:not(.is-hidden)').length, 27);
assert.deepEqual(Array.from(document.querySelectorAll('[data-role-template]:not(.is-hidden)')).map(button => button.dataset.templateCategory), Array(9).fill(['male', 'female', 'other']).flat());
click('[data-template-tab="male"]');
assert.equal(document.querySelectorAll('[data-role-template]:not(.is-hidden)').length, 9);
assert.ok(Array.from(document.querySelectorAll('[data-role-template]:not(.is-hidden)')).every(button => button.dataset.templateCategory === 'male'));
click('[data-template-tab="female"]');
assert.equal(document.querySelectorAll('[data-role-template]:not(.is-hidden)').length, 9);
assert.match(document.querySelector('[data-role-template="lin-xiaoyu"]').textContent, /陈佳宁[\s\S]*动画专业大一学生、校园社团分镜师[\s\S]*18岁[\s\S]*女/);
click('[data-template-tab="other"]');
assert.equal(document.querySelectorAll('[data-role-template]:not(.is-hidden)').length, 9);
assert.ok(Array.from(document.querySelectorAll('[data-role-template]:not(.is-hidden)')).every(button => button.dataset.templateCategory === 'other'));
assert.match(document.querySelector('[data-role-template="pao-rong"]').textContent, /泡绒[\s\S]*卡通幻想生物·未寄信邮差[\s\S]*其他/);
assert.doesNotMatch(document.querySelector('[data-role-template="pao-rong"]').textContent, /岁/);
click('[data-template-tab="all"]'); assert.equal(document.querySelectorAll('[data-role-template]:not(.is-hidden)').length, 27);
app.components.closeSubsheet();
field('name', '测试搭档'); field('systemPrompt', '你是测试搭档，清晰回答问题。'); submit();
await until(() => document.querySelector('#selectionSummary'), 'guided conversation form');
assert.equal(document.querySelector('#modalSubmit').disabled, false);
assert.equal(document.querySelector('[name="kind"]'), null); assert.equal(document.querySelector('[name="recentFullMessages"]'), null, 'the per-conversation retained-N slider must be gone');
submit();
await until(() => document.querySelector('#messageInput'), 'chat opened');
// 对话刚开始（还没有消息）时的欢迎面板：角色头像本身就是按钮，点它打开标准角色编辑弹窗。
assert.ok(document.querySelector('.chat-welcome'), 'an empty conversation shows the welcome panel');
const welcomeAvatar = document.querySelector('.chat-welcome-avatar');
assert.ok(welcomeAvatar, 'the welcome avatars are clickable buttons');
assert.equal(welcomeAvatar.dataset.editWelcomeRole, (await app.data.store.list('roles'))[0].id);
assert.equal(welcomeAvatar.getAttribute('aria-label'), '编辑角色 测试搭档');
assert.ok(welcomeAvatar.querySelector('.avatar.large'), 'the welcome avatar keeps its large style inside the button');
click('.chat-welcome-avatar');
await until(() => document.querySelector('#modalForm [name="systemPrompt"]'), 'standard role editor from the welcome avatar');
assert.equal(field('name').value, '测试搭档');
assert.equal(field('systemPrompt').value, '你是测试搭档，清晰回答问题。');
app.components.closeModal(true, true); await tick();
assert.ok(document.querySelector('.chat-welcome-avatar'), 'closing the editor leaves the welcome panel intact');
console.log('passed: the welcome-panel avatar opens the standard role editor');
const conversations = await app.data.store.list('conversations');
assert.equal(conversations.length, 1);
const id = conversations[0].id;
assert.equal((await app.data.store.list('roles'))[0].name, '测试搭档');
console.log('passed: model service → role → conversation onboarding');

await app.navigate('roles');
const originalTemplateAvatarBlob = app.features.roles.templateAvatarBlob;
const originalMediaPut = app.data.media.put;
const originalMediaRemove = app.data.media.remove;
let removedTemplateAvatar = '';
app.features.roles.templateAvatarBlob = async () => new Blob(['avatar'], { type: 'image/jpeg' });
app.data.media.put = async () => ({ id: 'template-avatar-fixture' });
app.data.media.remove = async mediaId => { removedTemplateAvatar = mediaId; };
click('[data-add-role]'); await until(() => document.querySelector('[data-open-role-templates]'), 'new role template trigger');
assert.equal(field('behaviorGuidance').getAttribute('rows'), '4', 'behavior guidance is a four-row field');
assert.equal(field('systemPrompt').getAttribute('rows'), '4', 'identity and personality is a four-row field');
assert.match(field('behaviorGuidance').value, /我必须根据情景自主对话[\s\S]*我每次回复必须用第一人称[\s\S]*我必须独立思考/, 'a new role starts from the default behavior guidance');
const templateModelBefore = field('llmProfileId').value;
click('[data-open-role-templates]'); await until(() => document.querySelector('[data-role-template="lin-xiaoyu"]'), 'template gallery selection'); click('[data-template-tab="female"]');
click('[data-role-template="lin-xiaoyu"]'); await until(() => field('name').value === '陈佳宁', 'template applied');
assert.equal(document.querySelector('[data-role-avatar-name]').textContent, '陈佳宁');
assert.equal(field('systemPrompt').value, app.data.roleTemplates.items.find(item => item.id === 'lin-xiaoyu').systemPrompt);
assert.equal(field('behaviorGuidance').value, app.data.roleTemplates.items.find(item => item.id === 'lin-xiaoyu').behaviorGuidance, 'a template brings its own behavior guidance');
assert.equal(field('llmProfileId').value, templateModelBefore, 'template must not replace the selected model');
assert.match(document.querySelector('#avatarPreview img').getAttribute('src'), /lin-xiaoyu\.webp$/);
app.components.closeModal(); await until(() => removedTemplateAvatar === 'template-avatar-fixture', 'cancelled template avatar cleanup');
app.features.roles.templateAvatarBlob = originalTemplateAvatarBlob;
app.data.media.put = originalMediaPut;
app.data.media.remove = originalMediaRemove;
assert.equal((await app.data.store.list('roles')).length, 1, 'previewing a template must not create a role');
await app.openChat(id);
console.log('passed: schema 2 role template gallery applies profile fields and cleans up cancelled avatar');

click('#chatMenuButton'); await until(() => document.querySelector('[data-chat-menu="settings"]'), 'merged conversation settings menu');
assert.deepEqual(Array.from(document.querySelectorAll('[data-chat-menu]')).slice(0, 3).map(button => button.dataset.chatMenu), ['settings', 'voice', 'summary']);
let generatedSceneRequest;
app.services.llm.generateScene = async (moderator, participants, conversation, userProfile, modes, guidance) => {
  generatedSceneRequest = { moderator, participants, conversation, userProfile, modes, guidance };
  return { text: '深夜，雨中的旧车站只剩最后一盏灯。远处传来列车缓慢靠站的声音。' };
};
click('[data-chat-menu="settings"]'); await until(() => document.querySelector('#modalForm [name="openingScene"]'), 'merged settings sheet');
assert.equal(document.querySelector('#modalTitle').textContent, '常规设定');
assert.ok(document.querySelector('.modal-sheet.conversation-settings-sheet'), 'the merged settings use the fixed-height sheet');
assert.deepEqual(Array.from(document.querySelectorAll('[data-conversation-tab]')).map(button => button.textContent), ['基础设定', '个人设定', '场景设定']);
assert.deepEqual(Array.from(document.querySelectorAll('[data-conversation-tab]')).map(button => button.getAttribute('aria-selected')), ['true', 'false', 'false']);
click('[data-conversation-tab="scene"]');
assert.ok(document.querySelector('[data-conversation-panel="scene"]:not(.is-hidden)'), 'scene settings are a sub-tab of the same modal');
assert.equal(document.querySelector('[data-conversation-panel="basic"]').className.includes('is-hidden'), true, 'only one settings sub-tab is visible at a time');
assert.deepEqual(Array.from(document.querySelectorAll('[data-scene-tab]')).map(button => button.textContent), ['手工设定', '自动生成']);
assert.equal(document.querySelector('.scene-settings-content > .helper'), null, 'legacy scene explanation is removed');
click('[data-scene-tab="auto"]');
assert.ok(document.querySelector('[data-scene-panel="auto"]:not(.is-hidden)'));
assert.deepEqual(Array.from(document.querySelectorAll('[data-scene-mode]')).map(button => button.textContent), ['闲聊', '思辨', '学习', '工作', '倾诉']);
assert.match(fs.readFileSync(root + 'styles/app.css', 'utf8'), /\.scene-mode-chip \+ \.scene-mode-chip \{ margin-left: 8px; \}/);
assert.equal(document.querySelector('[name="sceneGenerationPrompt"]').getAttribute('placeholder'), '补充关键词');
assert.equal(document.querySelector('[name="sceneGenerationPrompt"]').tagName, 'INPUT');
assert.equal(document.querySelector('[data-generate-scene] span').textContent, '生成');
click('[data-scene-mode="思辨"]'); click('[data-scene-mode="学习"]');
assert.equal(document.querySelector('[data-scene-mode="思辨"]').getAttribute('aria-pressed'), 'false');
assert.equal(document.querySelectorAll('[data-scene-mode][aria-pressed="true"]').length, 1);
field('sceneGenerationPrompt', '围绕一张旧车票展开'); click('[data-generate-scene]');
await until(() => /远处传来列车/.test(field('openingScene').value), 'generated opening scene fills the editor');
assert.equal(generatedSceneRequest.moderator.name, '测试搭档'); assert.equal(generatedSceneRequest.participants.length, 1);
assert.deepEqual(Array.from(generatedSceneRequest.modes), ['学习']); assert.equal(generatedSceneRequest.guidance, '围绕一张旧车票展开');
assert.match(document.querySelector('[data-scene-generation-status]').textContent, /可继续编辑后保存/);
submit();
await until(() => document.querySelector('.message-row.system'), 'opening scene materialized');
let sceneMessages = await app.data.store.messages(id);
assert.equal(sceneMessages.length, 1); assert.equal(sceneMessages[0].kind, 'system'); assert.equal(sceneMessages[0].systemType, 'scene');
assert.match(sceneMessages[0].text, /远处传来列车/);
assert.equal(document.querySelector('.message-row.system .message-name').textContent, '系统');
assert.equal(document.querySelector('.message-row.system .message-avatar-trigger'), null); assert.equal(document.querySelector('.message-row.system [data-regenerate-message]'), null);
click('.message-row.system [aria-label="编辑这条消息"]'); await until(() => document.querySelector('#modalForm [name="text"]'), 'ordinary scene message edit');
field('text', '深夜，雨中的旧车站只剩一盏灯。'); submit(); await until(() => !document.querySelector('#modalForm'), 'scene message edit saved');
sceneMessages = await app.data.store.messages(id); assert.equal(sceneMessages.length, 1); assert.equal(sceneMessages[0].text, '深夜，雨中的旧车站只剩一盏灯。');
console.log('passed: opening scene materializes once as an editable system message');

type('#messageInput', '离开后保留这份草稿');
await app.navigate('conversations');
assert.match(document.querySelector('.draft-preview').textContent, /保留这份草稿/);
await app.openChat(id);
assert.equal(document.querySelector('#messageInput').value, '离开后保留这份草稿');
let calls = 0;
app.services.llm.complete = async () => { calls++; return { text: '<script>unsafe()</script>纯文本回复', images: [], usage: null }; };
click('#sendButton');
await until(() => calls === 1 && !app.features.chatSession.active(id), 'send completes');
await tick(); await tick();
assert.equal((await app.data.store.messages(id)).length, 3);
assert.equal(document.querySelector('#messageInput').value, '');
assert.equal(document.querySelector('#messageListInner script'), null);
assert.match(document.querySelector('#messageListInner').textContent, /<script>unsafe\(\)<\/script>/);
console.log('passed: draft persistence, message sending, safe model text');

await app.features.conversations.manage(id);
click('[data-menu="settings"]');
await until(() => document.querySelector('#selectionSummary'), 'edit conversation');
field('title', '重新命名的对话'); submit();
await until(() => document.querySelector('#pageTitle').textContent === '重新命名的对话', 'renamed');
await app.navigate('conversations');
type('#listSearch', '不存在的关键词'); assert.match(document.querySelector('#conversationList').textContent, /没有找到/);
type('#listSearch', '重新命名'); assert.equal(document.querySelectorAll('[data-open]').length, 2); assert.ok(Array.from(document.querySelectorAll('[data-open]')).every(button => button.dataset.open === id));
console.log('passed: editing conversation and list filtering');

// 基础设定里的角色头像直接打开标准角色编辑弹窗；回来时这一轮所有子 tab 的未保存输入都要还在。
await app.features.conversations.manage(id);
click('[data-menu="settings"]'); await until(() => document.querySelector('[data-edit-participant]'), 'merged settings participants');
field('title', '未保存的标题草稿');
click('[data-edit-participant]'); await until(() => document.querySelector('#modalForm [name="behaviorGuidance"]'), 'participant avatar opens the standard role editor');
assert.equal(field('behaviorGuidance').getAttribute('rows'), '4');
assert.equal(field('systemPrompt').getAttribute('rows'), '4');
assert.equal(document.querySelector('#modalForm [name="name"]').value, '测试搭档');
app.components.closeModal();
await until(() => document.querySelector('#modalForm [name="title"]'), 'merged settings reopened after the role editor');
assert.equal(field('title').value, '未保存的标题草稿', 'unsubmitted settings survive the role-editor round trip');
assert.ok(document.querySelector('[data-edit-participant]'), 'the participants list is rebuilt in the reopened settings');
app.components.closeModal(); await tick();
assert.equal(document.querySelector('#modalForm'), null, 'cancelling the merged settings leaves nothing behind');
console.log('passed: participant avatar opens the standard role editor and returns to the merged settings');

// 行为指导不能只存在界面上：它必须随角色一起进入发给模型的上下文。
const guidanceRole = { id: 'guidance-role', name: '陈佳宁', systemPrompt: '我是陈佳宁，动画专业大一学生。', behaviorGuidance: '我必须自己把对话推下去，注意节奏。\n我每次只用第一人称说很少几句。', llmProfileId: '', model: '' };
const guidancePeer = { id: 'guidance-peer', name: '泡绒', systemPrompt: '我是泡绒，云端邮差。', behaviorGuidance: '我先把对方没说出口的部分接住。', llmProfileId: '', model: '' };
// 先取共享拼装函数的结果：applyToRole 会就地改写角色对象，顺序反了会拿到被覆盖后的身份性格。
assert.equal(app.services.context.roleReference(guidanceRole), '角色「陈佳宁」：\n我是陈佳宁，动画专业大一学生。\n行为指导：\n我必须自己把对话推下去，注意节奏。\n我每次只用第一人称说很少几句。', 'the shared role reference must join identity and guidance');
assert.doesNotMatch(app.services.context.roleReference({ id: 'x', name: '无指导', systemPrompt: '只有身份。' }), /行为指导/, 'a role without guidance must not gain an empty guidance heading');
const roleContext = app.services.context.applyToRole(guidanceRole, [guidanceRole, guidancePeer], { name: '测试用户', introduction: '喜欢直接、清晰的回答。' }).systemPrompt;
assert.match(roleContext, /<active_role>[\s\S]*我是陈佳宁，动画专业大一学生。[\s\S]*<\/active_role>[\s\S]*<behavior_guidance>[\s\S]*我必须自己把对话推下去，注意节奏。\n我每次只用第一人称说很少几句。[\s\S]*<\/behavior_guidance>/, 'the active role behavior guidance must follow its identity block');
assert.match(roleContext, /<other_roles_reference>[\s\S]*泡绒[\s\S]*我先把对方没说出口的部分接住。/, 'other participants must carry their own behavior guidance');
console.log('passed: behavior guidance travels with the role into the model context');

await app.openChat(id);
const unchangedMessage = document.querySelector('.message-row');
app.services.llm.complete = async () => { throw Error('模拟服务暂时不可用'); };
type('#messageInput', '失败后重试'); click('#sendButton');
await until(() => document.querySelector('.message-error') && !app.features.chatSession.active(id), 'failed reply rendered');
await tick(); await tick();
const retry = document.querySelector('.message-bubble .button');
assert.equal(retry.disabled, false, 'retry must be enabled after leaving busy state');
assert.equal(document.querySelector('.message-row'), unchangedMessage, 'unchanged message nodes are reused');
app.services.llm.complete = async () => ({ text: '重试恢复', images: [] }); retry.click();
await until(() => document.querySelector('#messageListInner').textContent.includes('重试恢复') && !app.features.chatSession.active(id), 'retry recovered');
assert.equal((await app.data.store.messages(id)).length, 5);
let entered, late;
const requestStarted = new Promise(resolve => { entered = resolve; });
app.services.llm.complete = async () => { entered(); return new Promise(resolve => { late = resolve; }); };
type('#messageInput', '停止这次请求'); click('#sendButton'); await requestStarted;
assert.equal(document.querySelector('#sendButton').getAttribute('aria-label'), '停止本轮回复');
click('#sendButton');
await until(() => !app.features.chatSession.active(id), 'turn stopped');
late({ text: '迟到的结果', images: [] }); await tick(); await tick();
assert.equal((await app.data.store.messages(id)).at(-1).status, 'cancelled');
assert.equal(document.querySelector('#messageListInner').textContent.includes('迟到的结果'), false);
console.log('passed: enabled retry after error, stable message nodes, UI stop with late response');

await app.navigate('settings');
const general = document.querySelector('#generalForm'); assert.ok(general);
assert.equal(general.querySelector('[name="recentFullMessages"]'), null, 'the retained-N count is derived from characters, so no message-count control exists anywhere');
// 压缩区间只有三个字数滑竿：触发 / 保留 / 目标，条数不再出现。
const compressionPanel = general.querySelector('[data-settings-panel="compression"]');
const retainSlider = compressionPanel.querySelector('[name="compressionRetainChars"]');
assert.ok(retainSlider, 'the retention length slider must exist');
assert.deepEqual([retainSlider.getAttribute('min'), retainSlider.getAttribute('max'), retainSlider.getAttribute('step'), retainSlider.getAttribute('value')], ['2000', '10000', '1000', '4000']);
const triggerSlider = compressionPanel.querySelector('[name="compressionThresholdChars"]');
assert.deepEqual([triggerSlider.getAttribute('min'), triggerSlider.getAttribute('max'), triggerSlider.getAttribute('value')], ['4000', '32000', '10000']);
assert.doesNotMatch(document.body.textContent, /固定携带最近消息|最近完整消息数量/, 'no message-count copy may survive');
// 「按 Enter 发送」已取消：Enter 始终换行，Ctrl / ⌘ + Enter 始终发送。
assert.equal(general.querySelector('[name="enterToSend"]'), null, 'the Enter-to-send toggle must be gone');
// 分类名从「关于」改为「系统」，顶部第一个元素是「备份软件和数据」。
click('.settings-tabs [data-settings-tab="system"]');
const systemPanel = document.querySelector('[data-settings-panel="system"]');
assert.ok(systemPanel, 'the system panel exists');
assert.equal(systemPanel.firstElementChild.dataset.backupApp, '', 'the backup button is the first thing in the system panel');
assert.equal(document.querySelector('.settings-tabs [data-settings-tab="about"]'), null, 'the About tab is now the system tab');
assert.match(systemPanel.textContent, /备份软件和数据[\s\S]*zhyuzh3d/, 'the app facts stay under the backup button');
// 测试宿主里没有 HermitApp 桥：点它必须如实报错，而不是静默什么都不做。
click('[data-backup-app]'); await tick(); await tick(); await tick();
assert.match(document.querySelector('#toastRoot .toast').textContent, /不在 HermitApp 中/);
click('.settings-tabs [data-settings-tab="interface"]');
click('[data-picker="theme"]'); await until(() => document.querySelector('.subsheet [data-choice="dark"]'), 'custom theme sheet');
click('.subsheet [data-choice="dark"]'); await tick(); assert.equal(general.querySelector('[name="theme"]').value, 'dark');
general.dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true }));
await until(() => document.documentElement.getAttribute('data-theme') === 'dark', 'theme saved');
await app.navigate('roles'); click('[data-edit-role]'); await until(() => document.querySelector('#modalForm [name="systemPrompt"]'), 'role editor');
assert.equal(document.querySelector('[data-open-role-templates]'), null, 'existing role editor must not expose the template gallery');
assert.ok(document.querySelector('button.avatar-picker[data-choose-avatar]')); assert.equal(document.querySelector('.avatar-editor').textContent.includes('选择本地图片'), false);
assert.match(fs.readFileSync(root + 'app/components/ui.js', 'utf8'), /data-crop-stage/); assert.doesNotMatch(fs.readFileSync(root + 'app/components/ui.js', 'utf8'), /name="crop[XY]"/);
assert.ok(document.querySelector('#temperatureField').classList.contains('is-hidden'), 'unsupported temperature is hidden');
assert.equal(document.querySelector('#ttsModelField'), null); assert.ok(document.querySelector('#ttsVoiceField').classList.contains('is-hidden')); assert.ok(document.querySelector('#voicePromptField').classList.contains('is-hidden'));
let previewText, previewRole; app.services.tts.speak = async (text, role) => { previewText = text; previewRole = role; };
click('[data-preview-tts]'); await until(() => previewText, 'role TTS preview'); assert.equal(previewText, '你好！欢迎使用朗读功能。'); assert.equal(previewRole.ttsProfileId, 'system-tts');
const roleNameBeforeChoice = field('name').value; click('[data-picker="llmProfileId"]'); await until(() => document.querySelector('.subsheet [data-choice]'), 'nested model choice sheet');
click('.subsheet [data-choice]'); await tick(); assert.equal(field('name').value, roleNameBeforeChoice, 'closing a nested choice sheet preserves the role form');
assert.equal(document.querySelector('#modalForm [name="model"]'), null); assert.ok(document.querySelector('#reasoningField').classList.contains('is-hidden'), 'unsupported reasoning is hidden'); app.components.closeModal();
await app.navigate('models', { modelsTab: 'llm' });
await app.data.store.put('llm-profiles', 'xai-empty', { id: 'xai-empty', name: 'xAI / Grok', family: 'xai', apiStyle: 'openai-chat', endpoint: 'https://api.x.ai/v1/chat/completions', apiKey: 'fixture', models: [], enabled: true });
let xaiDiscoveryRequest, xaiTestRequest;
app.platform.network.requestJson = async options => {
  if (options.method === 'GET') { xaiDiscoveryRequest = options; return { data: { models: [{ id: 'grok-fixture', input_modalities: ['text', 'image'], output_modalities: ['text'] }] } }; }
  xaiTestRequest = options; return { data: { choices: [{ message: { content: 'OK' } }] } };
};
await app.features.models.renderServices('llm');
click('[data-edit-service="xai-empty"]'); await until(() => document.querySelector('[data-fetch-models]'), 'legacy empty xAI model editor');
click('[data-fetch-models]'); await until(() => /grok-fixture/.test(document.querySelector('[data-picker="externalModelId"] [data-picker-label]').textContent), 'xAI directory loaded');
click('[data-test-model]'); await until(() => xaiTestRequest && /连接成功/.test(document.querySelector('#connectionStatus').textContent), 'legacy empty xAI model repaired through discovery');
submit(); await until(() => !document.querySelector('#modalForm'), 'repaired xAI service saved');
assert.equal((await app.data.store.get('llm-profiles', 'xai-empty')).externalModelId, 'grok-fixture');
assert.equal(xaiDiscoveryRequest.url, 'https://api.x.ai/v1/language-models');
assert.equal(JSON.parse(xaiTestRequest.bodyText).model, 'grok-fixture');
assert.match(document.querySelector('[data-test-service="xai-empty"]').textContent, /^测试$/);
const xaiCard = document.querySelector('[data-test-service="xai-empty"]').closest('.model-service-card');
const xaiEndpoint = xaiCard.querySelector('.service-endpoint');
assert.ok(xaiEndpoint, 'the address row is rendered for a configured service');
assert.equal(xaiEndpoint.querySelector('[data-test-service]'), document.querySelector('[data-test-service="xai-empty"]'), 'the test button sits at the end of the address row');
assert.deepEqual(Array.from(xaiCard.querySelectorAll('.service-manage > .button')).map(button => [button.textContent, Boolean(button.querySelector('i'))]), [['复制', true], ['编辑', true], ['删除', true]], 'copy, edit and delete share one row and each carries an icon plus a label');
assert.equal(xaiCard.querySelector('.service-manage .icon-button'), null, 'no icon-only action button is left in the management row');
const modelsToolbar = document.querySelector('.section-toolbar');
assert.equal(modelsToolbar.firstElementChild.tagName, 'BUTTON', 'the add button leads the toolbar');
assert.equal(modelsToolbar.lastElementChild.tagName, 'P', 'the explanatory note sits below the add button');
assert.match(modelsToolbar.lastElementChild.textContent, /每张卡片对应一个模型/);
console.log('passed: empty xAI service discovers, enables and tests a language model');
// 连接测试是可选的：目录获取成功之后可以直接保存，未测试的卡片保存为 unverified。
await app.data.store.put('llm-profiles', 'xai-untested', { id: 'xai-untested', name: 'xAI / Untested', family: 'xai', apiStyle: 'openai-chat', endpoint: 'https://api.x.ai/v1/chat/completions', apiKey: 'fixture', models: [], enabled: true });
await app.features.models.renderServices('llm');
click('[data-edit-service="xai-untested"]'); await until(() => document.querySelector('#modalSubmit'), 'untested model editor');
assert.equal(document.querySelector('#modalSubmit').dataset.mode, 'fetch');
click('[data-fetch-models]'); await until(() => /grok-fixture/.test(document.querySelector('[data-picker="externalModelId"] [data-picker-label]').textContent), 'untested catalog loaded');
assert.equal(document.querySelector('#modalSubmit').textContent, '保存设置');
submit(); await until(() => !document.querySelector('#modalForm'), 'a fetched catalog saves without a connection test');
assert.equal(document.querySelector('.error-box'), null);
assert.equal((await app.data.store.get('llm-profiles', 'xai-untested')).validationState, 'unverified', 'saving without testing records an unverified model');
assert.equal((await app.data.store.get('llm-profiles', 'xai-untested')).externalModelId, 'grok-fixture');
console.log('passed: a fetched catalog saves without a connection test');
let savedElevenLabs;
app.platform.network.requestJson = async options => options.url.includes('/v1/models')
  ? { data: [{ model_id: 'eleven_multilingual_v2', name: 'Eleven Multilingual v2', can_do_text_to_speech: true }] }
  : { data: { voices: [{ voice_id: 'voice-fixture', name: 'Fixture Voice' }], has_more: false } };
app.services.tts.testService = async () => ({ modelId: 'eleven_multilingual_v2', voiceId: 'voice-fixture' });
await app.navigate('models', { modelsTab: 'tts' });
app.features.models.openService('tts', null, next => { savedElevenLabs = next; });
field('family', 'elevenlabs').dispatchEvent(new window.Event('change', { bubbles: true }));
field('apiKey', 'fixture-eleven'); click('[data-fetch-models]');
await until(() => /Eleven Multilingual v2/.test(document.querySelector('[data-picker="externalModelId"] [data-picker-label]').textContent), 'ElevenLabs directory succeeds');
click('[data-test-model]'); await until(() => /连接成功/.test(document.querySelector('#connectionStatus').textContent), 'ElevenLabs model and voice baseline succeeds');
submit(); await until(() => savedElevenLabs, 'connected ElevenLabs service saves without a false changed-signature error');
assert.equal(savedElevenLabs.voices[0].id, 'voice-fixture');
assert.equal(savedElevenLabs.voices[0].name, 'Fixture Voice');
assert.ok(savedElevenLabs.enabledModelIds.includes('eleven_multilingual_v2'));
assert.equal(document.querySelector('.error-box'), null);
console.log('passed: ElevenLabs connection result saves immediately after model and voice discovery');
const legacyElevenLabs = await app.data.store.get('tts-profiles', savedElevenLabs.id);
legacyElevenLabs.voices = [{ id: 'voice-fixture' }];
await app.data.store.put('tts-profiles', legacyElevenLabs.id, legacyElevenLabs);
await app.navigate('roles'); click('[data-edit-role]');
await until(() => document.querySelector('#modalForm [name="ttsProfileId"]'), 'role editor repairs legacy ElevenLabs voice labels');
field('ttsProfileId', legacyElevenLabs.id).dispatchEvent(new window.Event('change', { bubbles: true })); await tick();
assert.equal(document.querySelector('[data-picker="ttsVoice"] [data-picker-label]').textContent, 'Fixture Voice');
click('[data-picker="ttsVoice"]'); await until(() => document.querySelector('.subsheet [data-choice="voice-fixture"]'), 'role voice picker opens with repaired label');
assert.equal(document.querySelector('.subsheet [data-choice="voice-fixture"] span').textContent, 'Fixture Voice');
app.components.closeSubsheet(); app.components.closeModal();
assert.equal((await app.data.store.get('tts-profiles', legacyElevenLabs.id)).voices[0].name, 'Fixture Voice');
console.log('passed: role ElevenLabs picker uses account voice names and repairs legacy ID-only catalogs');
await app.navigate('models', { modelsTab: 'llm' });
const secretProfile = await app.data.store.get('llm-profiles', 'xai-empty');
secretProfile.apiKey = 'demoCredentialAlphaOmega';
secretProfile.customHeaders = JSON.stringify({ Authorization: 'Bearer demoHeaderAlphaOmega', 'X-Client-Key': 'demoClientAlphaOmega' });
await app.data.store.put('llm-profiles', secretProfile.id, secretProfile); await app.features.models.renderServices('llm');
let clipboardSecret = ''; app.platform.hermit.readClipboardText = async () => clipboardSecret;
click('[data-edit-service="xai-empty"]'); await until(() => document.querySelector('#modalForm [name="apiKey"]'), 'edit model');
assert.equal(document.querySelector('[name="apiKey"]').type, 'password'); assert.equal(document.querySelector('[name="apiKey"]').value, 'demoCredentialAlphaOmega');
assert.equal(document.querySelectorAll('.secret-editor [name="apiKey"]').length, 1); assert.equal(document.querySelector('[name="clear_apiKey"]'), null);
assert.equal(document.querySelector('.secret-mask').textContent, 'demo••••••mega');
assert.equal(document.querySelector('[name="customHeaders"]').type, 'password'); assert.equal(document.querySelector('[name="customHeaders"]').value, secretProfile.customHeaders);
assert.equal(document.body.textContent.includes('demoCredentialAlphaOmega'), false, 'saved API key must not be rendered as visible text');
assert.equal(document.body.textContent.includes('demoHeaderAlphaOmega'), false, 'saved Header secret must not be rendered as visible text');
const apiKeyVisibility = document.querySelector('.secret-editor [name="apiKey"] ~ [data-toggle-secret]');
click('.secret-editor [name="apiKey"] ~ [data-toggle-secret]'); assert.equal(document.querySelector('[name="apiKey"]').type, 'text'); assert.ok(apiKeyVisibility.querySelector('.fa-eye-slash'));
click('.secret-editor [name="apiKey"] ~ [data-toggle-secret]'); assert.equal(document.querySelector('[name="apiKey"]').type, 'password'); assert.ok(apiKeyVisibility.querySelector('.fa-eye'));
clipboardSecret = 'demoCredentialAlphaOmega'; click('[data-paste-key]'); await until(() => document.querySelector('[name="apiKey"]').value === clipboardSecret, 'paste saved API key from clipboard');
clipboardSecret = secretProfile.customHeaders; click('[data-paste-headers]'); await until(() => document.querySelector('[name="customHeaders"]').value === clipboardSecret, 'paste saved Header credentials from clipboard');
submit(); await until(() => !document.querySelector('#modalForm'), 'save unchanged masked credentials');
assert.equal((await app.data.store.get('llm-profiles', 'xai-empty')).apiKey, 'demoCredentialAlphaOmega');
assert.equal((await app.data.store.get('llm-profiles', 'xai-empty')).customHeaders, secretProfile.customHeaders);
uiConfirmTest: {
  app.components.closeModal();
  let dismissed;
  const waiting = app.components.confirm({ title: '确认测试', message: '遮罩关闭也要有终态' }).then(result => { dismissed = result; });
  click('.modal-backdrop'); await waiting;
  assert.equal(dismissed, false);
}
let escaped;
const escapedConfirmation = app.components.confirm({ title: 'Escape', message: 'test' }).then(value => { escaped = value; });
const escape = new window.Event('keydown', { bubbles: true, cancelable: true }); escape.key = 'Escape'; document.dispatchEvent(escape); await escapedConfirmation;
assert.equal(escaped, false);
await Promise.all([app.navigate('roles'), app.navigate('models', { modelsTab: 'asr' })]);
assert.equal(app.state.route, 'models'); assert.equal(document.querySelector('#modelsContent').getAttribute('aria-labelledby'), 'models-tab-asr');
assert.deepEqual(Array.from(document.querySelectorAll('.section-tabs button')).map(button => button.textContent), ['对话模型', '朗读模型', '语音输入']);
assert.equal(document.querySelector('.section-tabs i'), null, 'model category tabs have no icons');
assert.equal(document.querySelector('[data-edit-service="system-asr"]'), null, 'unavailable system ASR must not expose an editor');
assert.equal(document.querySelector('[data-test-service="system-asr"]'), null, 'unavailable system ASR must not expose a recording test');
assert.match(document.querySelector('.model-service-card').textContent, /不可用/, 'unavailable system ASR must be labelled clearly');
console.log('passed: settings/theme, masked credentials with clipboard paste and explicit reveal, confirmation dismissal and rapid navigation');
app.components.closeModal();

await app.navigate('me');
const userForm = document.querySelector('#userProfileForm'); assert.ok(userForm); assert.ok(userForm.querySelector('.avatar-picker.round'));
userForm.elements.namedItem('name').value = '测试用户'; userForm.elements.namedItem('introduction').value = '喜欢直接、清晰的回答。';
userForm.dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true }));
await tick(); await tick();
assert.equal((await app.data.store.get('meta', 'user-profile')).name, '测试用户');
assert.equal((await app.data.store.get('meta', 'user-profile')).introduction, '喜欢直接、清晰的回答。');
assert.equal(document.querySelectorAll('#bottomNav [data-route]').length, 5);
await app.navigate('conversations');
assert.equal(document.querySelector('.page-heading'), null); assert.equal(document.querySelector('[data-filter]'), null); assert.match(document.querySelector('#pageTitle').textContent, /chataxi.*v\d+\.\d+\.\d+/);
const firstRole = (await app.data.store.list('roles'))[0];
app.data.media.toDataUrl = async mediaId => ({
  'role-avatar-fixture': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAB',
  'user-avatar-fixture': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAC'
}[mediaId] || '');
const savedUserProfile = await app.data.store.get('meta', 'user-profile'); savedUserProfile.avatarMediaId = 'user-avatar-fixture'; await app.data.store.put('meta', 'user-profile', savedUserProfile);
firstRole.avatarMediaId = 'role-avatar-fixture'; await app.data.store.put('roles', firstRole.id, firstRole);
const secondRole = { ...firstRole, id: 'second-role', name: '第二个超长角色', avatarMediaId: '' };
await app.data.store.put('roles', secondRole.id, secondRole);
const group = await app.data.store.get('conversations', id); group.kind = 'group'; group.roleIds = [firstRole.id, secondRole.id]; group.activeRoleIds = group.roleIds.slice(); await app.data.store.put('conversations', id, group);
await app.navigate('conversations'); assert.match(document.querySelector('.meta').textContent, /群聊\s\|\s测试搭档 · 第二个超长角色/);
const conversationCard = document.querySelector('.conversation-card');
assert.ok(conversationCard.querySelector('.conversation-head > .avatar-stack + .list-copy'), 'the head row keeps the avatar and the text column together');
assert.equal(conversationCard.querySelector('.meta').parentElement.className, 'card-button conversation-open', 'the role-name row spans the whole card body instead of the indented text column');
assert.equal(conversationCard.querySelector('.list-copy .meta'), null, 'the role-name row must not stay inside the text column');
assert.equal(document.querySelectorAll('.conversation-action-rail').length, 1); assert.ok(document.querySelector('.conversation-action-open .fa-comment')); assert.ok(document.querySelector('[data-manage] .fa-gear'));
click('[data-manage]'); await until(() => document.querySelector('[data-menu="settings"]'), 'conversation management sheet'); app.components.closeModal();
click('.conversation-action-open'); await until(() => document.querySelector('#pageTitle').textContent === '重新命名的对话', 'conversation rail open');
assert.ok(document.querySelector('.composer-recipients')); assert.equal(document.querySelector('.chat-role-strip'), null);
assert.equal(document.querySelectorAll('.composer-recipients .mention-avatar').length, 2); assert.equal(document.querySelector('[data-all-roles]'), null);
assert.equal(document.querySelector('[data-role-toggle="' + secondRole.id + '"] .mention-name').textContent, '第二个超...');
assert.equal(document.querySelectorAll('[data-role-toggle][aria-pressed="true"]').length, 1);
click('#chatMenuButton'); await until(() => document.querySelector('[data-chat-menu="voice"]'), 'chat voice menu'); click('[data-chat-menu="voice"]'); await until(() => document.querySelector('[name="autoSpeak"]'), 'conversation readout settings');
assert.match(document.querySelector('#streamTtsPlaybackStatus').textContent, /完整音频播放/, 'system TTS reports its actual playback path without a manual stream switch'); app.components.closeModal();
click('[data-role-toggle="' + secondRole.id + '"]');
assert.equal(document.querySelectorAll('[data-role-toggle][aria-pressed="true"]').length, 1);
let mentioned;
app.services.llm.complete = async role => { mentioned = role.id; return { text: '继续完成', images: [] }; };
click('#sendButton');
await until(() => mentioned === secondRole.id && !app.features.chatSession.active(id), 'empty mention continues one role');
const latestTurn = (await app.data.store.messages(id)).slice(-2); assert.match(latestTurn[0].text, /@第二个超长角色.*继续回答/); assert.equal(latestTurn[1].roleId, secondRole.id);
await tick(); await tick();
assert.ok(document.querySelector('[data-regenerate-message]')); assert.ok(document.querySelector('[aria-label="编辑这条消息"] .fa-pencil'));
let editGenerated = 0; app.services.llm.complete = async () => { editGenerated++; return { text: '不应生成', images: [] }; };
click('[data-message-id="' + latestTurn[1].id + '"] [aria-label="编辑这条消息"]'); await until(() => document.querySelector('#modalForm [name="text"]'), 'message edit sheet');
assert.equal(document.querySelector('#modalSubmit').textContent, '保存'); assert.equal(document.querySelector('#modalForm [name="regenerate"]'), null);
field('text', '只保存修改后的回复'); submit(); await until(() => !document.querySelector('#modalForm'), 'message edit saves without generation');
assert.equal((await app.data.store.messages(id)).find(message => message.id === latestTurn[1].id).text, '只保存修改后的回复'); assert.equal(editGenerated, 0);
assert.equal(document.querySelectorAll('.message-row.assistant [data-edit-chat-role]').length > 0, true, 'every stored role avatar opens the role editor');
assert.ok(document.querySelector('[data-message-id="' + latestTurn[1].id + '"] [data-edit-chat-role="' + secondRole.id + '"]'), 'text fallback role avatar still edits its role');
click('.message-row.assistant [data-edit-chat-role="' + firstRole.id + '"]'); await until(() => document.querySelector('#modalForm [name="systemPrompt"]'), 'message role avatar opens the role editor sheet');
field('name', '即时更新搭档'); field('systemPrompt', '这是在对话中保存的新角色设定。'); submit();
await until(() => !document.querySelector('#modalForm') && /即时更新搭档/.test(document.querySelector('#pageSubtitle').textContent), 'saved role refreshes the open chat');
assert.equal(document.querySelector('[data-role-toggle="' + firstRole.id + '"] .mention-name').textContent, '即时更新...');
let hotRole; app.services.llm.complete = async role => { hotRole = role; return { text: '已使用新设定', images: [] }; };
click('[data-role-toggle="' + firstRole.id + '"]'); type('#messageInput', '验证角色修改立即生效'); click('#sendButton');
await until(() => hotRole && !app.features.chatSession.active(id), 'next reply uses role saved from the message avatar sheet');
assert.equal(hotRole.name, '即时更新搭档'); assert.equal(hotRole.systemPrompt, '这是在对话中保存的新角色设定。');
click('.message-row.user [data-edit-conversation-profile="user"]'); await until(() => document.querySelector('#modalForm [name="userName"]'), 'user message avatar opens conversation personal settings');
assert.equal(document.querySelector('#modalTitle').textContent, '常规设定');
assert.equal(document.querySelector('[data-conversation-tab="personal"]').getAttribute('aria-selected'), 'true', 'the user avatar opens the profile sub-tab of the merged settings');
assert.equal(document.querySelector('#conversationAvatarPreview .avatar').dataset.avatarMedia || '', (await app.data.store.get('meta', 'user-profile')).avatarMediaId || '', 'conversation avatar defaults to the global personal avatar');
assert.equal(field('userName').value, '测试用户', 'conversation identity starts from the global name');
assert.equal(field('userIntroduction').value, '喜欢直接、清晰的回答。', 'conversation identity starts from the global introduction');
field('userName', '本对话的我'); field('userIntroduction', '只用于这个对话的介绍。'); submit();
await until(() => !document.querySelector('#modalForm') && document.querySelector('.message-row.user .message-name').textContent === '本对话的我', 'saved conversation profile refreshes user messages');
const personalized = await app.data.store.get('conversations', id); assert.equal(personalized.userName, '本对话的我'); assert.equal(personalized.userIntroduction, '只用于这个对话的介绍。');
let nextUserContext; app.services.llm.complete = async (_role, _history, _task, _conversation, _roles, userProfile) => { nextUserContext = userProfile; return { text: '已使用个人设定', images: [] }; };
type('#messageInput', '验证个人设定立即生效'); click('#sendButton');
await until(() => nextUserContext && !app.features.chatSession.active(id), 'next reply uses the saved conversation profile');
assert.deepEqual(JSON.parse(JSON.stringify(nextUserContext)), { name: '本对话的我', introduction: '只用于这个对话的介绍。' });
click('.message-row.user [data-edit-conversation-profile="user"]'); await until(() => document.querySelector('#modalForm [name="userName"]'), 'conversation identity reopens with saved values');
field('userName', ''); field('userIntroduction', ''); submit();
await until(() => !document.querySelector('#modalForm') && document.querySelector('.message-row.user .message-name').textContent === '测试用户', 'cleared conversation identity falls back to global profile');
const clearedPersonalized = await app.data.store.get('conversations', id); assert.equal(clearedPersonalized.userName, ''); assert.equal(clearedPersonalized.userIntroduction, '');
let releaseRouting, releaseAnswer;
app.services.llm.selectRole = async (_moderator, candidates) => new Promise(resolve => { releaseRouting = () => resolve(candidates.find(role => role.id === secondRole.id)); });
app.services.llm.complete = async role => new Promise(resolve => { releaseAnswer = () => resolve({ text: role.name + '自主回答', images: [] }); });
click('#autoRoleToggle'); await until(() => document.querySelector('#autoRoleToggle').getAttribute('aria-checked') === 'true', 'automatic role selection enabled');
click('#sendButton');
await until(() => releaseRouting && document.querySelector('.routing-indicator') && document.querySelector('#messageListInner').textContent.includes('请你们自主回答。'), 'empty automatic turn and routing indicator rendered');
assert.equal(document.querySelector('.routing-indicator .typing-bubble').children.length, 3);
releaseRouting();
await until(() => releaseAnswer && !document.querySelector('.routing-indicator') && Array.from(document.querySelectorAll('.message-row.assistant')).at(-1).querySelector('.typing-bubble'), 'routing indicator replaced by selected role typing bubble');
releaseAnswer(); await until(() => !app.features.chatSession.active(id), 'automatic role answer completed');
const automaticTurn = (await app.data.store.messages(id)).slice(-2); assert.equal(automaticTurn[0].text, '请你们自主回答。'); assert.equal(automaticTurn[1].roleId, secondRole.id);
const beforeBulk = (await app.data.store.messages(id)).at(-1).createdAt;
await Promise.all(Array.from({ length: 150 }, (_, index) => app.data.store.putMessage({ id: 'bulk-' + index, conversationId: id, kind: 'user', text: '长对话性能消息 ' + index, media: [], status: 'done', createdAt: beforeBulk + index + 1 })));
await app.features.chat.renderMessages();
assert.equal(document.querySelectorAll('.message-row').length, 120, 'chat initially mounts only the latest bounded message window');
assert.match(document.querySelector('.history-window-control').textContent, /加载更早消息/);
click('.history-window-control button'); await until(() => document.querySelectorAll('.message-row').length > 120, 'older messages load incrementally');
let stopCalls = 0; app.services.tts.stop = async () => { stopCalls++; };
click('#muteTtsButton'); await tick(); await tick(); assert.equal((await app.data.store.get('conversations', id)).ttsMuted, true, 'mute preference saved');
assert.ok(document.querySelector('#muteTtsButton .fa-volume-xmark')); assert.equal(stopCalls, 0, 'mute does not stop current playback');
app.events.emit('tts:state', { speaking: true, muted: true }); assert.ok(document.querySelector('#muteTtsButton').classList.contains('voice-active')); assert.ok(document.querySelector('#muteTtsButton .fa-volume-xmark'));
app.events.emit('tts:state', { speaking: false, muted: true }); assert.equal(document.querySelector('#muteTtsButton').classList.contains('voice-active'), false);
await app.navigate('conversations'); await app.openChat(id); assert.equal(document.querySelector('[data-role-toggle="' + secondRole.id + '"]').getAttribute('aria-pressed'), 'true', 'last automatically selected role is remembered');
assert.equal(document.querySelector('select, datalist'), null, 'rendered flows do not use native list menus');
// ── 自动压缩之后的冻结历史：原消息不能再改，只能改「压缩概要」 ──────────────
const frozenTimeline = await app.data.store.messages(id);
const boundaryMessage = frozenTimeline[frozenTimeline.length - 21];
await app.data.store.put('summaries', id, { id, conversationId: id, text: '第一版概要', throughMessageId: boundaryMessage.id, throughMessageCreatedAt: boundaryMessage.createdAt, sourceMessageCount: frozenTimeline.length - 20, retainedMessageCount: 6, compressedByRoleId: secondRole.id, compressedByRoleName: secondRole.name, updatedAt: Date.now() });
await app.features.chat.renderMessages(); await tick();
const boundaryRow = document.querySelector('[data-message-id="' + boundaryMessage.id + '"]');
assert.ok(boundaryRow.classList.contains('is-frozen'), 'messages inside the summary boundary render as frozen history');
assert.equal(boundaryRow.querySelector('.frozen-badge').textContent, '已压缩');
assert.equal(boundaryRow.querySelector('.frozen-badge').getAttribute('title'), '这条消息已经压缩进概要，不再按原文参与上下文，也不能单独修改');
const frozenPencil = boundaryRow.querySelector('[aria-label="编辑这条消息"]');
assert.ok(frozenPencil.classList.contains('is-disabled'), 'the frozen pencil looks disabled');
assert.equal(frozenPencil.getAttribute('aria-disabled'), 'true');
document.querySelectorAll('.message-row.is-frozen [data-regenerate-message]').forEach(button => { assert.ok(button.classList.contains('is-disabled')); assert.equal(button.getAttribute('aria-disabled'), 'true'); });
frozenPencil.click(); await tick(); await tick();
assert.equal(document.querySelector('#toastRoot .toast').textContent, '历史已被压缩，请修改压缩概要');
assert.equal(document.querySelector('#modalForm'), null, 'a frozen pencil never opens the message editor');
const uncompressedRow = document.querySelector('.message-row:not(.is-frozen)');
assert.equal(uncompressedRow.querySelector('[aria-label="编辑这条消息"]').getAttribute('aria-disabled'), null, 'messages after the summary boundary stay editable');
assert.ok(uncompressedRow.querySelector('[data-regenerate-message]') || uncompressedRow.classList.contains('user'), 'assistant replies after the boundary keep their regenerate action');
// ── 对话菜单里的「压缩概要」必须可编辑、可保存 ────────────────────────────
click('#chatMenuButton'); await until(() => document.querySelector('[data-chat-menu="summary"]'), 'chat menu exposes the compression summary');
assert.equal(document.querySelector('[data-chat-menu="summary"]').textContent, '压缩概要 · 已生成');
click('[data-chat-menu="summary"]'); await until(() => document.querySelector('#modalForm [name="summary0"]'), 'compression summary sheet');
assert.equal(document.querySelector('#modalTitle').textContent, '编辑压缩概要');
// 概要正文通常很长：弹窗固定占 80% 高，说明文字之外的高度全给输入框（高度判据在 verify.mjs）。
assert.ok(document.querySelector('.modal-sheet.summary-sheet'), 'the summary editor uses the fixed-height sheet');
assert.ok(document.querySelector('#modalForm .summary-edit > .field > .prompt-editor'), 'the summary textarea owns the flexible row of that sheet');
assert.equal(field('summary0').value, '第一版概要');
field('summary0', '   '); submit(); await tick(); await tick();
assert.equal(document.querySelector('.form-error').textContent, '压缩概要不能为空');
assert.ok(document.querySelector('#modalForm'), 'an empty summary is rejected without closing the sheet');
field('summary0', '手工修订后的概要'); submit(); await until(() => !document.querySelector('#modalForm'), 'compression summary saves and closes');
const editedSummary = await app.data.store.get('summaries', id);
assert.equal(editedSummary.text, '手工修订后的概要'); assert.equal(editedSummary.throughMessageId, boundaryMessage.id); assert.ok(editedSummary.editedAt > 0);
assert.equal(document.querySelector('#toastRoot .toast').textContent, '压缩概要已更新');
assert.equal(app.services.context.requestMessages({ summary: editedSummary, recent: [] })[0].text, '手工修订后的概要', 'the edited summary replaces the frozen history in the next request');
console.log('passed: five tabs, user profile, compact mention, mute state and message regeneration controls');
console.log('DOM flow checks passed (no layout, browser, device or provider acceptance claimed)');
process.exit(0);
